markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
pygments: true
permalink: /:year/:month/:day/:title.html
pagination: 10
